# Generated by Django 3.2 on 2022-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorucoz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyWeatherByCity',
        ),
    ]
