# Generated by Django 3.2 on 2021-08-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenemeTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('type', models.CharField(choices=[('AYT', 'AYT'), ('TYT', 'TYT')], max_length=255, verbose_name='Deneme Tipi')),
                ('tyt_turkce', models.IntegerField(verbose_name='TYT Türkçe Neti')),
                ('tyt_matematik', models.IntegerField(verbose_name='TYT Matematik Neti')),
                ('tyt_fen', models.IntegerField(verbose_name='TYT Fen Neti')),
                ('tyt_sosyal', models.IntegerField(verbose_name='TYT Sosyal Neti')),
                ('ayt_matematik', models.IntegerField(verbose_name='AYT Matematik Neti')),
                ('ayt_fizik', models.IntegerField(verbose_name='AYT Fizik Neti')),
                ('ayt_kimya', models.IntegerField(verbose_name='AYT Kimya Neti')),
                ('ayt_biyoloji', models.IntegerField(verbose_name='AYT Biyoloji Neti')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denemetakip', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
        ),
    ]
