# Generated by Django 3.2 on 2021-08-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemetakip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denemetakip',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Varsa Notunuz'),
        ),
        migrations.AlterField(
            model_name='denemetakip',
            name='type',
            field=models.CharField(choices=[('TYT', 'TYT'), ('AYT', 'AYT')], max_length=255, verbose_name='Deneme Tipi'),
        ),
    ]
