# Generated by Django 3.2 on 2022-06-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemetakip', '0004_auto_20220624_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denemetakip',
            name='type',
            field=models.CharField(choices=[('AYT', 'AYT'), ('TYT', 'TYT')], max_length=255, verbose_name='Deneme Tipi'),
        ),
    ]
