# Generated by Django 3.2 on 2022-06-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemetakip', '0006_alter_denemetakip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denemetakip',
            name='toplamNet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denemetakip',
            name='type',
            field=models.CharField(choices=[('AYT', 'AYT'), ('TYT', 'TYT')], max_length=255, verbose_name='Deneme Tipi'),
        ),
    ]
