# Generated by Django 3.2 on 2022-06-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemetakip', '0007_auto_20220624_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denemetakip',
            name='ayt_biyoloji',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='ayt_fizik',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='ayt_kimya',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='ayt_matematik',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='toplamNet',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='type',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='tyt_fen',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='tyt_matematik',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='tyt_sosyal',
        ),
        migrations.RemoveField(
            model_name='denemetakip',
            name='tyt_turkce',
        ),
        migrations.AddField(
            model_name='denemetakip',
            name='netSayisi',
            field=models.IntegerField(default=1, verbose_name='Toplam Net'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denemetakip',
            name='publisher',
            field=models.CharField(default=1, max_length=255, verbose_name='Yayınevi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='denemetakip',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Deneme Adı'),
        ),
    ]
