# Generated by Django 3.2 on 2022-10-26 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denemetakip', '0009_auto_20221026_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='denemetakipayt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='denemetakipayt', to='auth.user', verbose_name='Öğrenci'),
            preserve_default=False,
        ),
    ]
