# Generated by Django 3.2 on 2022-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemetakip', '0010_denemetakipayt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='denemetakipayt',
            name='netSayisi',
            field=models.IntegerField(default=1, verbose_name='ToplamNet'),
            preserve_default=False,
        ),
    ]
