# Generated by Django 3.2 on 2022-11-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denemetakip', '0011_denemetakipayt_netsayisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denemetakip',
            name='created_date',
            field=models.DateTimeField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='denemetakipayt',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Tarih'),
        ),
    ]
