# Generated by Django 3.2 on 2023-11-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denemetakip', '0012_auto_20221115_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denemetakipayt',
            options={'ordering': ['-created_date']},
        ),
    ]
