# Generated by Django 3.2 on 2021-08-08 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(choices=[('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik')], max_length=50, verbose_name='Ders')),
                ('subject', models.CharField(choices=[('Paragrafta Anlam', 'Paragrafta Anlam'), ('Sözcükte Anlam', 'Sözcükte Anlam'), ('Cümlede Anlam', 'Cümlede Anlam')], max_length=255, verbose_name='Ders')),
                ('sound', models.FileField(upload_to='', verbose_name='Podcast Kaydı')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
