# Generated by Django 3.2 on 2021-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('TYT Türkçe', 'TYT Türkçe')], max_length=50, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subject',
            field=models.CharField(choices=[('Paragrafta Anlam', 'Paragrafta Anlam'), ('Cümlede Anlam', 'Cümlede Anlam'), ('Sözcükte Anlam', 'Sözcükte Anlam')], max_length=255, verbose_name='Ders'),
        ),
    ]
