# Generated by Django 3.2 on 2021-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20210808_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='subject',
            field=models.CharField(choices=[('Sözcükte Anlam', 'Sözcükte Anlam'), ('Cümlede Anlam', 'Cümlede Anlam'), ('Paragrafta Anlam', 'Paragrafta Anlam')], max_length=255, verbose_name='Ders'),
        ),
    ]
