# Generated by Django 3.2 on 2021-08-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_auto_20210820_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('TYT Türkçe', 'TYT Türkçe')], max_length=50, verbose_name='Ders'),
        ),
    ]
