# Generated by Django 3.2 on 2022-06-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_podcast_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='subject',
            field=models.CharField(choices=[('Cümlede Anlam', 'Cümlede Anlam'), ('Sözcükte Anlam', 'Sözcükte Anlam'), ('Paragrafta Anlam', 'Paragrafta Anlam')], max_length=255, verbose_name='Ders'),
        ),
    ]
