# Generated by Django 3.2 on 2022-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_alter_podcast_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='lesson',
            field=models.CharField(choices=[('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik')], max_length=50, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subject',
            field=models.CharField(choices=[('Paragrafta Anlam', 'Paragrafta Anlam'), ('Cümlede Anlam', 'Cümlede Anlam'), ('Sözcükte Anlam', 'Sözcükte Anlam')], max_length=255, verbose_name='Ders'),
        ),
    ]
