# Generated by Django 3.2 on 2022-06-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_auto_20220622_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('TYT Türkçe', 'TYT Türkçe')], max_length=50, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subject',
            field=models.CharField(choices=[('Paragrafta Anlam', 'Paragrafta Anlam'), ('Sözcükte Anlam', 'Sözcükte Anlam'), ('Cümlede Anlam', 'Cümlede Anlam')], max_length=255, verbose_name='Ders'),
        ),
    ]
