# Generated by Django 3.2 on 2022-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0015_auto_20221026_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('TYT Türkçe', 'TYT Türkçe')], max_length=50, verbose_name='Ders'),
        ),
    ]
