# Generated by Django 3.2 on 2022-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0016_alter_podcast_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='subject',
            field=models.CharField(choices=[('Sözcükte Anlam', 'Sözcükte Anlam'), ('Paragrafta Anlam', 'Paragrafta Anlam'), ('Cümlede Anlam', 'Cümlede Anlam')], max_length=255, verbose_name='Ders'),
        ),
    ]
