# Generated by Django 5.0.6 on 2024-06-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0019_auto_20231126_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='subject',
            field=models.CharField(choices=[('Cümlede Anlam', 'Cümlede Anlam'), ('Sözcükte Anlam', 'Sözcükte Anlam'), ('Paragrafta Anlam', 'Paragrafta Anlam')], max_length=255, verbose_name='Ders'),
        ),
    ]
