# Generated by Django 5.1.4 on 2024-12-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0020_alter_podcast_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('TYT Türkçe', 'TYT Türkçe')], max_length=50, verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subject',
            field=models.CharField(choices=[('Paragrafta Anlam', 'Paragrafta Anlam'), ('Sözcükte Anlam', 'Sözcükte Anlam'), ('Cümlede Anlam', 'Cümlede Anlam')], max_length=255, verbose_name='Ders'),
        ),
    ]
