# Generated by Django 3.2 on 2021-08-08 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSihirbazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(choices=[('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Fizik', 'AYT Fizik'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik'), ('AYT Matematik', 'AYT Matematik')], max_length=50, verbose_name='Ders Adı')),
                ('net_araligi', models.CharField(choices=[('25-30', '25-30'), ('10-20', '10-20'), ('30-40', '30-40'), ('20-25', '20-25'), ('0-10', '0-10')], max_length=50, verbose_name='Net Aralığınız')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(choices=[('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Fizik', 'AYT Fizik'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('TYT Matematik', 'TYT Matematik'), ('AYT Matematik', 'AYT Matematik'), ('TYT Fen Bilimleri', 'TYT Fen Bilimleri')], max_length=30, verbose_name='Ders Adı')),
                ('subject', models.CharField(max_length=150, verbose_name='Konu Adı')),
                ('time', models.IntegerField(max_length=5000, verbose_name='Çalışma Süresi (Dakika)')),
                ('question', models.IntegerField(max_length=5000, verbose_name='Soru Sayısı')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NetOkul', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
