# Generated by Django 3.2 on 2021-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('TYT Fen Bilimleri', 'TYT Fen Bilimleri'), ('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('AYT Fizik', 'AYT Fizik'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Matematik', 'AYT Matematik')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Fizik', 'AYT Fizik'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Matematik', 'AYT Matematik')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('20-25', '20-25'), ('0-10', '0-10'), ('10-20', '10-20'), ('30-40', '30-40'), ('25-30', '25-30')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
