# Generated by Django 3.2 on 2021-08-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20210810_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('AYT Matematik', 'AYT Matematik'), ('AYT Fizik', 'AYT Fizik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Matematik', 'TYT Matematik'), ('TYT Fen Bilimleri', 'TYT Fen Bilimleri'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Biyoloji', 'AYT Biyoloji')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Matematik', 'AYT Matematik'), ('AYT Fizik', 'AYT Fizik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Matematik', 'TYT Matematik'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Biyoloji', 'AYT Biyoloji')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('30-40', '30-40'), ('0-10', '0-10'), ('20-25', '20-25'), ('10-20', '10-20'), ('25-30', '25-30')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
