# Generated by Django 3.2 on 2022-06-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20210820_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('AYT Fizik', 'AYT Fizik'), ('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Matematik', 'TYT Matematik'), ('TYT Fen Bilimleri', 'TYT Fen Bilimleri'), ('AYT Kimya', 'AYT Kimya'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Matematik', 'AYT Matematik')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Fizik', 'AYT Fizik'), ('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Matematik', 'AYT Matematik')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('20-25', '20-25'), ('25-30', '25-30'), ('30-40', '30-40'), ('0-10', '0-10'), ('10-20', '10-20')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
