# Generated by Django 3.2 on 2022-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20220622_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('AYT Matematik', 'AYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Fen Bilimleri', 'TYT Fen Bilimleri'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Fizik', 'AYT Fizik')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Matematik', 'AYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Fizik', 'AYT Fizik')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('30-40', '30-40'), ('0-10', '0-10'), ('25-30', '25-30'), ('10-20', '10-20'), ('20-25', '20-25')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
