# Generated by Django 3.2 on 2022-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20220622_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Matematik', 'AYT Matematik'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Kimya', 'AYT Kimya'), ('TYT Fen Bilimleri', 'TYT Fen Bilimleri'), ('AYT Fizik', 'AYT Fizik'), ('TYT Matematik', 'TYT Matematik'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Matematik', 'AYT Matematik'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Kimya', 'AYT Kimya'), ('AYT Fizik', 'AYT Fizik'), ('TYT Matematik', 'TYT Matematik')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('20-25', '20-25'), ('10-20', '10-20'), ('25-30', '25-30'), ('0-10', '0-10'), ('30-40', '30-40')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
