# Generated by Django 3.2 on 2022-06-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20220624_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('TYT Fen Bilimleri', 'TYT Fen Bilimleri'), ('AYT Fizik', 'AYT Fizik'), ('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('AYT Matematik', 'AYT Matematik'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Fizik', 'AYT Fizik'), ('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Matematik', 'AYT Matematik'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('0-10', '0-10'), ('10-20', '10-20'), ('25-30', '25-30'), ('30-40', '30-40'), ('20-25', '20-25')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
