# Generated by Django 3.2 on 2022-06-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20220624_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('AYT Fizik', 'AYT Fizik'), ('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Fen Bilimleri', 'TYT Fen Bilimleri'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Matematik', 'AYT Matematik'), ('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Fizik', 'AYT Fizik'), ('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Matematik', 'AYT Matematik'), ('AYT Biyoloji', 'AYT Biyoloji')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('30-40', '30-40'), ('20-25', '20-25'), ('10-20', '10-20'), ('0-10', '0-10'), ('25-30', '25-30')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
