# Generated by Django 3.2 on 2022-10-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20220918_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('TYT Biyoloji', 'TYT Biyoloji'), ('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik'), ('AYT Matematik', 'AYT Matematik'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('AYT Fizik', 'AYT Fizik'), ('TYT Kimya', 'TYT Kimya'), ('TYT Fizik', 'TYT Fizik')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='schoolnote',
            name='question',
            field=models.IntegerField(verbose_name='Soru Sayısı'),
        ),
        migrations.AlterField(
            model_name='schoolnote',
            name='time',
            field=models.IntegerField(verbose_name='Çalışma Süresi (Dakika)'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Matematik', 'TYT Matematik'), ('AYT Matematik', 'AYT Matematik'), ('AYT Fizik', 'AYT Fizik')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('0-10', '0-10'), ('25-30', '25-30'), ('20-25', '20-25'), ('10-20', '10-20'), ('30-40', '30-40')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
