# Generated by Django 3.2 on 2022-10-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20221026_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('TYT Fizik', 'TYT Fizik'), ('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Biyoloji', 'TYT Biyoloji'), ('AYT Matematik', 'AYT Matematik'), ('TYT Kimya', 'TYT Kimya'), ('AYT Fizik', 'AYT Fizik')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Matematik', 'AYT Matematik'), ('AYT Fizik', 'AYT Fizik')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('20-25', '20-25'), ('0-10', '0-10'), ('10-20', '10-20'), ('25-30', '25-30'), ('30-40', '30-40')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
