# Generated by Django 3.2 on 2022-10-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20221026_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('TYT Kimya', 'TYT Kimya'), ('TYT Biyoloji', 'TYT Biyoloji'), ('TYT Matematik', 'TYT Matematik'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('AYT Matematik', 'AYT Matematik'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Kimya', 'AYT Kimya'), ('AYT Fizik', 'AYT Fizik'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Fizik', 'TYT Fizik')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('AYT Matematik', 'AYT Matematik'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Kimya', 'AYT Kimya'), ('AYT Fizik', 'AYT Fizik'), ('TYT Türkçe', 'TYT Türkçe')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('0-10', '0-10'), ('10-20', '10-20'), ('30-40', '30-40'), ('20-25', '20-25'), ('25-30', '25-30')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
