# Generated by Django 3.2 on 2023-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20221115_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Kimya', 'AYT Kimya'), ('TYT Matematik', 'TYT Matematik'), ('TYT Fizik', 'TYT Fizik'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Biyoloji', 'TYT Biyoloji'), ('AYT Fizik', 'AYT Fizik'), ('AYT Matematik', 'AYT Matematik'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('TYT Kimya', 'TYT Kimya')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Kimya', 'AYT Kimya'), ('TYT Matematik', 'TYT Matematik'), ('TYT Türkçe', 'TYT Türkçe'), ('AYT Matematik', 'AYT Matematik'), ('AYT Fizik', 'AYT Fizik')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('10-20', '10-20'), ('25-30', '25-30'), ('30-40', '30-40'), ('0-10', '0-10'), ('20-25', '20-25')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
