# Generated by Django 5.0.6 on 2024-06-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20231126_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('TYT Türkçe', 'TYT Türkçe'), ('TYT Kimya', 'TYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('AYT Fizik', 'AYT Fizik'), ('TYT Biyoloji', 'TYT Biyoloji'), ('AYT Matematik', 'AYT Matematik'), ('TYT Fizik', 'TYT Fizik'), ('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('TYT Türkçe', 'TYT Türkçe'), ('AYT Fizik', 'AYT Fizik'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Matematik', 'AYT Matematik'), ('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('0-10', '0-10'), ('10-20', '10-20'), ('30-40', '30-40'), ('20-25', '20-25'), ('25-30', '25-30')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
