# Generated by Django 5.1.4 on 2024-12-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_schoolnote_lesson_alter_testsihirbazi_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolnote',
            name='lesson',
            field=models.CharField(choices=[('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Fizik', 'AYT Fizik'), ('TYT Türkçe', 'TYT Türkçe'), ('TYT Fizik', 'TYT Fizik'), ('TYT Matematik', 'TYT Matematik'), ('AYT Matematik', 'AYT Matematik'), ('TYT Sosyal Bilimler', 'TYT Sosyal Bilimler'), ('TYT Kimya', 'TYT Kimya'), ('TYT Biyoloji', 'TYT Biyoloji')], max_length=30, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='lesson',
            field=models.CharField(choices=[('TYT Matematik', 'TYT Matematik'), ('AYT Kimya', 'AYT Kimya'), ('AYT Biyoloji', 'AYT Biyoloji'), ('AYT Matematik', 'AYT Matematik'), ('AYT Fizik', 'AYT Fizik'), ('TYT Türkçe', 'TYT Türkçe')], max_length=50, verbose_name='Ders Adı'),
        ),
        migrations.AlterField(
            model_name='testsihirbazi',
            name='net_araligi',
            field=models.CharField(choices=[('0-10', '0-10'), ('20-25', '20-25'), ('30-40', '30-40'), ('10-20', '10-20'), ('25-30', '25-30')], max_length=50, verbose_name='Net Aralığınız'),
        ),
    ]
